// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_contact from "./routes/api/contact.ts";
import * as $index from "./routes/index.tsx";
import * as $Animations from "./islands/Animations.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $Cube from "./islands/Cube.tsx";
import * as $PageLoading from "./islands/PageLoading.tsx";
import * as $Spaceship from "./islands/Spaceship.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/contact.ts": $api_contact,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Animations.tsx": $Animations,
    "./islands/Carousel.tsx": $Carousel,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/Cube.tsx": $Cube,
    "./islands/PageLoading.tsx": $PageLoading,
    "./islands/Spaceship.tsx": $Spaceship,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
