// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/contact.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Animations.tsx";
import * as $$1 from "./islands/Carousel.tsx";
import * as $$2 from "./islands/ContactForm.tsx";
import * as $$3 from "./islands/Cube.tsx";
import * as $$4 from "./islands/Spaceship.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/contact.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Animations.tsx": $$0,
    "./islands/Carousel.tsx": $$1,
    "./islands/ContactForm.tsx": $$2,
    "./islands/Cube.tsx": $$3,
    "./islands/Spaceship.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
